### ISSUE TITLE
Unable to Run Newly Created App

### ISSUE THREAD

**Issue by Splode** [nuxt-community/create-nuxt-app#39]
After creating a new `Universal` app and running either `npm run dev` or `npm run build`, npm exits with error.

## Expected Behavior
Expect a dev server to spool up and serve the Nuxt application when running either `npm run dev`.

## Current Behavior
npm exits with the following error:

```bash
C:\..\nuxt-test\node_modules\nuxt\lib\core\middleware\nuxt.js:72
      const policies = this.options.render.csp.policies ? {...this.options.render.csp.policies} : null
                                                           ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\..\nuxt-test\node_modules\nuxt\lib\core\renderer.js:19:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nuxt-test@1.0.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nuxt-test@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

## Steps to Reproduce

1. With `create-nuxt-app` installed globally, run `create-nuxt-app <app-name>`
2. Select `Universal` as the `rendering mode`
3. `cd <app-name> && npm run dev`

## Context (Environment)
Node version `8.0.0`
npm version `5.0.0`

## Detailed Description
I encounter this issue when attempting to create a fresh universal Nuxt application. I have no additional modules or plugins added.

**Comment by Splode** [comment]
## Solved
This issue was solved by upgrading Node to the LTS version:
Node version `8.9.4`
npm version `5.6.0`
