### ISSUE TITLE
Creation of new app is crashing (Options: Express + vuetify + Universal + Axios)

### ISSUE THREAD

**Issue by o1lab** [nuxt-community/create-nuxt-app#40]
Options provided to npx create-nuxt-app are as below

```
? Project name vuetify
? Project description My splendiferous Nuxt.js project
? Use a custom server framework express
? Use a custom UI framework vuetify
? Choose rendering mode Universal
? Use axios module yes
? Use eslint no
? Author name o1lab
? Choose a package manager npm
```

On npm run dev
```
node_modules/nuxt/lib/core/middleware/nuxt.js:72
      const policies = this.options.render.csp.policies ? {...this.options.render.csp.policies} : null
                                                           ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (...../node_modules/nuxt/lib/core/renderer.js:19:24)
[nodemon] app crashed - waiting for file changes before starting...

```

**Comment by o1lab** [comment]
I just noticed problem not seen in node v8.9.4.
Problem was seen in node v8.2.1.
