### ISSUE TITLE
Cannot find module 'eslint-config-prettier' after fresh installation

### ISSUE THREAD

**Issue by romikzo** [nuxt-community/create-nuxt-app#99]
### Version

[v2.1.0](https://github.com/create-nuxt-app/releases/tag/v2.1.0)

### Reproduction link

[http://localhost:3000](http://localhost:3000)

### Steps to reproduce

Just run `yarn create nuxt-app <my-project>` and select 'Install prettier' as 'Yes'. After, `yarn run dev` gives error.

### What is expected ?

Installing and running without errors.

### What is actually happening?

```Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Cannot find module 'eslint-config-prettier'
Referenced from: /Users/romikzo/Projects/s-maria-frontend/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js
Referenced from: /Users/romikzo/Projects/s-maria-frontend/.eslintrc.js
    at ModuleResolver.resolve (/Users/romikzo/Projects/s-maria-frontend/node_modules/eslint/lib/util/module-resolver.js:72:19)
    at resolve (/Users/romikzo/Projects/s-maria-frontend/node_modules/eslint/lib/config/config-file.js:484:28)
    at load (/Users/romikzo/Projects/s-maria-frontend/node_modules/eslint/lib/config/config-file.js:556:26)
    at configExtends.reduceRight (/Users/romikzo/Projects/s-maria-frontend/node_modules/eslint/lib/config/config-file.js:430:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/romikzo/Projects/s-maria-frontend/node_modules/eslint/lib/config/config-file.js:408:26)
    at loadFromDisk (/Users/romikzo/Projects/s-maria-frontend/node_modules/eslint/lib/config/config-file.js:528:22)
    at load (/Users/romikzo/Projects/s-maria-frontend/node_modules/eslint/lib/config/config-file.js:564:20)
    at configExtends.reduceRight (/Users/romikzo/Projects/s-maria-frontend/node_modules/eslint/lib/config/config-file.js:430:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/romikzo/Projects/s-maria-frontend/node_modules/eslint/lib/config/config-file.js:408:26)
    at loadFromDisk (/Users/romikzo/Projects/s-maria-frontend/node_modules/eslint/lib/config/config-file.js:528:22)
    at Object.load (/Users/romikzo/Projects/s-maria-frontend/node_modules/eslint/lib/config/config-file.js:564:20)
    at Config.getLocalConfigHierarchy (/Users/romikzo/Projects/s-maria-frontend/node_modules/eslint/lib/config.js:227:44)
    at Config.getConfigHierarchy (/Users/romikzo/Projects/s-maria-frontend/node_modules/eslint/lib/config.js:179:43)
    at Config.getConfigVector (/Users/romikzo/Projects/s-maria-frontend/node_modules/eslint/lib/config.js:286:21)
```
On `yarn run dev` after installation.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/create-nuxt-app/issues/c66">#c66</a>)</em></sub></div>

**Comment by aldarund** [comment]
fixed in 2.1.1
